import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { addLocale } from 'primereact/api'
import './index.css'

// ── Locale español para componentes PrimeReact (Calendar, etc.) ──
addLocale('es', {
    firstDayOfWeek: 1,
    dayNames: ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'],
    dayNamesShort: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
    dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
    monthNames: ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
    monthNamesShort: ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'],
    today: 'Hoy',
    clear: 'Limpiar',
    dateFormat: 'dd/mm/yy',
    weekHeader: 'Sem',
    choose: 'Elegir',
    upload: 'Subir',
    cancel: 'Cancelar',
    accept: 'Sí',
    reject: 'No',
    chooseDate: 'Elegir fecha',
    chooseYear: 'Elegir año',
    chooseMonth: 'Elegir mes',
    prevDecade: 'Década anterior',
    nextDecade: 'Década siguiente',
    prevYear: 'Año anterior',
    nextYear: 'Año siguiente',
    prevMonth: 'Mes anterior',
    nextMonth: 'Mes siguiente',
    prevHour: 'Hora anterior',
    nextHour: 'Hora siguiente',
    prevMinute: 'Minuto anterior',
    nextMinute: 'Minuto siguiente',
    prevSecond: 'Segundo anterior',
    nextSecond: 'Segundo siguiente',
    am: 'am',
    pm: 'pm',
    apply: 'Aplicar',
    matchAll: 'Coincidir todo',
    matchAny: 'Coincidir alguno',
    addRule: 'Agregar regla',
    removeRule: 'Eliminar regla',
    emptyMessage: 'No se encontraron resultados',
    emptyFilterMessage: 'No se encontraron resultados',
    aria: {
        trueLabel: 'Verdadero',
        falseLabel: 'Falso',
        nullLabel: 'No seleccionado',
        star: '1 estrella',
        stars: '{star} estrellas',
        selectAll: 'Todos los elementos seleccionados',
        unselectAll: 'Todos los elementos deseleccionados',
        close: 'Cerrar',
        previous: 'Anterior',
        next: 'Siguiente',
        navigation: 'Navegación',
        scrollTop: 'Desplazar hacia arriba',
        moveTop: 'Mover arriba',
        moveUp: 'Subir',
        moveDown: 'Bajar',
        moveBottom: 'Mover abajo',
        moveToTarget: 'Mover al destino',
        moveToSource: 'Mover al origen',
        moveAllToTarget: 'Mover todo al destino',
        moveAllToSource: 'Mover todo al origen',
        pageLabel: 'Página {page}',
        firstPageLabel: 'Primera página',
        lastPageLabel: 'Última página',
        nextPageLabel: 'Página siguiente',
        prevPageLabel: 'Página anterior',
        rowsPerPageLabel: 'Filas por página',
        jumpToPageDropdownLabel: 'Ir a página',
        jumpToPageInputLabel: 'Ir a página',
        selectRow: 'Fila seleccionada',
        unselectRow: 'Fila deseleccionada',
        expandRow: 'Fila expandida',
        collapseRow: 'Fila contraída',
        showFilterMenu: 'Mostrar menú de filtros',
        hideFilterMenu: 'Ocultar menú de filtros',
        filterOperator: 'Operador de filtro',
        filterConstraint: 'Restricción de filtro',
        editRow: 'Editar fila',
        saveEdit: 'Guardar edición',
        cancelEdit: 'Cancelar edición',
        listView: 'Vista de lista',
        gridView: 'Vista de cuadrícula',
        slide: 'Deslizar',
        slideNumber: 'Deslizar {slideNumber}',
        zoomImage: 'Ampliar imagen',
        zoomIn: 'Acercar',
        zoomOut: 'Alejar',
        rotateRight: 'Rotar a la derecha',
        rotateLeft: 'Rotar a la izquierda',
    },
})
// PrimeFlex — utilidades de layout (grid, flex, spacing, surface) del ecosistema PrimeReact
import 'primeflex/primeflex.css'
// El SCSS del layout se importa aquí para que Vite lo procese con Sass directamente
import '../styles/layout/layout.scss'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
